### ISSUE TITLE
Move repo to Dracula's official org

### ISSUE THREAD

**Issue by zenorocha** [dracula/desktop-telegram#1]
Hello @mazipan!

I'm the creator of Dracula color scheme. I was searching for themes created by the community and I found yours. Good job by the way!

I was wondering if you are interested in transferring this repository to the official organization (https://github.com/dracula). You'll continue maintaining this project, the only difference is that we can make it more visible and include it on the site (https://draculatheme.com).

What do you think?

**Comment by mazipan** [comment]
Honestly, very proud to know there is person that watching this repo.
So, how do you like to transfer this repo ?

**Comment by mazipan** [comment]
@zenorocha maybe you can add me to that organization, so I can transfer this repository ya

**Comment by zenorocha** [comment]
Awesome! Just sent you an invitation, let me know when you accept it.

**Comment by mazipan** [comment]
I just accepted.

**Comment by mazipan** [comment]
Just transferred
